var OPTION_SYNC_DATE = "2026-08-23";
var OPTIONS = [
{name:"沪深300股指期权", code:"IO", exch:"中金所", open:15, closePrev:15, closeToday:15, exercise:1, remark:"2026年行权费减半(原2元)"},
{name:"上证50股指期权",   code:"HO", exch:"中金所", open:15, closePrev:15, closeToday:15, exercise:1, remark:"2026年行权费减半(原2元)"},
{name:"中证1000股指期权", code:"MO", exch:"中金所", open:15, closePrev:15, closeToday:15, exercise:1, remark:"2026年行权费减半(原2元)"},
{name:"铜期权",       code:"CU", exch:"上期所", open:5,   closePrev:5,   closeToday:0, exercise:5},
{name:"黄金期权",     code:"AU", exch:"上期所", open:2,   closePrev:2,   closeToday:0, exercise:2},
{name:"铝期权",       code:"AL", exch:"上期所", open:1.5, closePrev:1.5, closeToday:0, exercise:1.5},
{name:"锌期权",       code:"ZN", exch:"上期所", open:1.5, closePrev:1.5, closeToday:0, exercise:1.5},
{name:"螺纹钢期权",   code:"RB", exch:"上期所", open:1.5, closePrev:1.5, closeToday:0, exercise:1.5},
{name:"白银期权",     code:"AG", exch:"上期所", open:2,   closePrev:2,   closeToday:0, exercise:2},
{name:"天然橡胶期权", code:"RU", exch:"上期所", open:1.5, closePrev:1.5, closeToday:0, exercise:1.5},
{name:"丁二烯橡胶期权", code:"BR", exch:"上期所", open:0.5, closePrev:0.5, closeToday:0, exercise:0.5},
{name:"燃料油期权",   code:"FU", exch:"上期所", open:1,   closePrev:1,   closeToday:0, exercise:1},
{name:"纸浆期权",     code:"SP", exch:"上期所", open:1.5, closePrev:1.5, closeToday:0, exercise:1.5},
{name:"沥青期权",     code:"BU", exch:"上期所", open:1,   closePrev:1,   closeToday:0, exercise:1},
{name:"铅期权",       code:"PB", exch:"上期所", open:1.5, closePrev:1.5, closeToday:0, exercise:1.5},
{name:"镍期权",       code:"NI", exch:"上期所", open:1.5, closePrev:1.5, closeToday:0, exercise:1.5},
{name:"锡期权",       code:"SN", exch:"上期所", open:1.5, closePrev:1.5, closeToday:0, exercise:1.5},
{name:"氧化铝期权",   code:"AO", exch:"上期所", open:3.5, closePrev:3.5, closeToday:0, exercise:3.5},
{name:"铸造铝合金期权", code:"AD", exch:"上期所", open:5, closePrev:5, closeToday:0, exercise:5},
{name:"胶版印刷纸期权", code:"OP", exch:"上期所", open:5, closePrev:5, closeToday:0, exercise:5},
{name:"白糖期权",   code:"SR", exch:"郑商所", open:1.5, closePrev:1.5, closeToday:0, exercise:1.5},
{name:"棉花期权",   code:"CF", exch:"郑商所", open:1.5, closePrev:1.5, closeToday:0, exercise:1.5},
{name:"PTA期权",    code:"TA", exch:"郑商所", open:0.5, closePrev:0.5, closeToday:0, exercise:0.5},
{name:"甲醇期权",   code:"MA", exch:"郑商所", open:0.5, closePrev:0.5, closeToday:0, exercise:0.5},
{name:"菜籽粕期权", code:"RM", exch:"郑商所", open:0.8, closePrev:0.8, closeToday:0, exercise:0.8},
{name:"菜籽油期权", code:"OI", exch:"郑商所", open:1.5, closePrev:1.5, closeToday:0, exercise:1.5},
{name:"尿素期权",   code:"UR", exch:"郑商所", open:1,   closePrev:1,   closeToday:0, exercise:1},
{name:"纯碱期权",   code:"SA", exch:"郑商所", open:0.5, closePrev:0.5, closeToday:0, exercise:0.5},
{name:"短纤期权",   code:"PF", exch:"郑商所", open:0.5, closePrev:0.5, closeToday:0, exercise:0.5},
{name:"烧碱期权",   code:"SH", exch:"郑商所", open:2,   closePrev:2,   closeToday:0, exercise:2},
{name:"对二甲苯期权", code:"PX", exch:"郑商所", open:1, closePrev:1, closeToday:0, exercise:1},
{name:"瓶片期权",   code:"PR", exch:"郑商所", open:1,   closePrev:1,   closeToday:0, exercise:1},
{name:"玻璃期权",   code:"FG", exch:"郑商所", open:0.5, closePrev:0.5, closeToday:0, exercise:0.5},
{name:"苹果期权",   code:"AP", exch:"郑商所", open:1,   closePrev:1,   closeToday:0, exercise:1},
{name:"红枣期权",   code:"CJ", exch:"郑商所", open:1,   closePrev:1,   closeToday:0, exercise:1},
{name:"花生期权",   code:"PK", exch:"郑商所", open:0.8, closePrev:0.8, closeToday:0, exercise:0.8},
{name:"硅铁期权",   code:"SF", exch:"郑商所", open:0.5, closePrev:0.5, closeToday:0, exercise:0.5},
{name:"锰硅期权",   code:"SM", exch:"郑商所", open:0.5, closePrev:0.5, closeToday:0, exercise:0.5},
{name:"动力煤期权", code:"ZC", exch:"郑商所", open:150, closePrev:150, closeToday:0, exercise:150, remark:"长期停牌"},
{name:"丙烯期权",   code:"PL", exch:"郑商所", open:1,   closePrev:1,   closeToday:0, exercise:1},
{name:"豆粕期权",   code:"M",  exch:"大商所", open:1,   closePrev:1,   closeToday:0.5, exercise:1, remark:"平今减半"},
{name:"玉米期权",   code:"C",  exch:"大商所", open:0.6, closePrev:0.6, closeToday:0.6, exercise:0.6},
{name:"铁矿石期权", code:"I",  exch:"大商所", open:2,   closePrev:2,   closeToday:2,   exercise:2},
{name:"棕榈油期权", code:"P",  exch:"大商所", open:0.5, closePrev:0.5, closeToday:0.5, exercise:1},
{name:"聚丙烯期权", code:"PP", exch:"大商所", open:0.5, closePrev:0.5, closeToday:0.5, exercise:1},
{name:"聚乙烯期权", code:"L",  exch:"大商所", open:0.5, closePrev:0.5, closeToday:0.5, exercise:1},
{name:"PVC期权",    code:"V",  exch:"大商所", open:0.5, closePrev:0.5, closeToday:0.5, exercise:1},
{name:"乙二醇期权", code:"EG", exch:"大商所", open:0.5, closePrev:0.5, closeToday:0.5, exercise:1},
{name:"苯乙烯期权", code:"EB", exch:"大商所", open:0.5, closePrev:0.5, closeToday:0.5, exercise:1},
{name:"焦煤期权",   code:"JM", exch:"大商所", open:0.5, closePrev:0.5, closeToday:0.5, exercise:0.5},
{name:"焦炭期权",   code:"J",  exch:"大商所", open:0.5, closePrev:0.5, closeToday:0.5, exercise:0.5},
{name:"液化石油气期权", code:"PG", exch:"大商所", open:1, closePrev:1, closeToday:1, exercise:1},
{name:"生猪期权",   code:"LH", exch:"大商所", open:1.5, closePrev:1.5, closeToday:1.5, exercise:1.5},
{name:"鸡蛋期权",   code:"JD", exch:"大商所", open:0.5, closePrev:0.5, closeToday:0.5, exercise:0.5},
{name:"豆油期权",   code:"Y",  exch:"大商所", open:0.5, closePrev:0.5, closeToday:0.5, exercise:1},
{name:"豆一期权",   code:"A",  exch:"大商所", open:0.5, closePrev:0.5, closeToday:0.5, exercise:1},
{name:"豆二期权",   code:"B",  exch:"大商所", open:0.2, closePrev:0.2, closeToday:0.2, exercise:0.5},
{name:"玉米淀粉期权", code:"CS", exch:"大商所", open:0.2, closePrev:0.2, closeToday:0.2, exercise:0.2},
{name:"原木期权",   code:"LG", exch:"大商所", open:1,   closePrev:1,   closeToday:1,   exercise:1},
{name:"纯苯期权",   code:"BZ", exch:"大商所", open:1,   closePrev:1,   closeToday:1,   exercise:1},
{name:"工业硅期权", code:"SI", exch:"广期所", open:2, closePrev:2, closeToday:0, exercise:2},
{name:"碳酸锂期权", code:"LC", exch:"广期所", open:3, closePrev:3, closeToday:0, exercise:3},
{name:"多晶硅期权", code:"PS", exch:"广期所", open:2, closePrev:2, closeToday:2, exercise:2},
{name:"铂期权",     code:"PT", exch:"广期所", open:2, closePrev:2, closeToday:0, exercise:2},
{name:"钯期权",     code:"PD", exch:"广期所", open:2, closePrev:2, closeToday:0, exercise:2},
{name:"原油期权",   code:"SC", exch:"能源中心", open:10,  closePrev:10,  closeToday:0, exercise:10},
{name:"20号胶期权", code:"NR", exch:"能源中心", open:1.5, closePrev:1.5, closeToday:0, exercise:1.5},
{name:"国际铜期权", code:"BC", exch:"能源中心", open:2,   closePrev:2,   closeToday:0, exercise:2}
];